
CREATE TABLE IF NOT EXISTS `user`(
	`rec_id` INT(11) NOT NULL AUTO_INCREMENT,
	`account`  VARCHAR(20) NOT NULL DEFAULT '' ,
	`password` VARCHAR(40) NOT NULL DEFAULT '' ,
	`nickname` VARCHAR(20) NOT NULL DEFAULT '',
	`email` VARCHAR(20) NOT NULL DEFAULT '',
	`deleted` ENUM('0','1') NOT NULL DEFAULT '0',
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`rec_id`),
	UNIQUE KEY `UK_USER_ACCOUNT`(`account`)
)ENGINE=INNODB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `module`(
	`type` TINYINT(4) NOT NULL ,
	`name` VARCHAR(15) NOT NULL ,
	`deleted` ENUM('0','1') NOT NULL DEFAULT '0',
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY(`type`),
	UNIQUE KEY `UK_MODULE_NAME`(`name`,`deleted`)
)ENGINE=INNODB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `task`(
	`rec_id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(150) NOT NULL DEFAULT '',
	`private` ENUM('0','1','2') NOT NULL DEFAULT '0' COMMENT '0 私有 1 圈子可见',
	`status` TINYINT(4) NOT NULL DEFAULT 10 COMMENT '5已取消  10  草稿 20 立项 30 执行中 40 部分完成 50 中途取消 60 完成',
	`creator_id` INT(11) NOT NULL,
	`module_id` TINYINT(4) NOT NULL,
	`desc` TEXT NOT NULL,
	`start_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`expect_finsh_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`finished_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`remark` VARCHAR(250) NOT NULL DEFAULT '',
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY(`rec_id`),
	KEY `TASK_INDEX_CREATOR`(`creator_id`,`status`),
	KEY `TASK_INDEX_MODULE`(`creator_id`,`module_id`),
	CONSTRAINT `FK_TASK_CREATOR_ID` FOREIGN KEY(`creator_id`) REFERENCES `user`(`rec_id`),
	CONSTRAINT `FK_TASK_MODULE_ID` FOREIGN KEY(`module_id`) REFERENCES `module`(`type`)
)ENGINE = INNODB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `task_detail`(
	`rec_id` INT(11) NOT NULL AUTO_INCREMENT,
	`task_id` INT(11) NOT NULL,
	`operator_id` INT(11) NOT NULL,
	`operate_type` TINYINT(4) NOT NULL DEFAULT '1' COMMENT ' 1 添加任务进展',
	`desc` TEXT NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY(`rec_id`),
	KEY `TASK_DETAIL_OPERATOR_TASK`(`operator_id`,`task_id`),
	CONSTRAINT `FK_TASK_DETAIL_TASK_ID` FOREIGN KEY (`task_id`) REFERENCES `task`(`rec_id`),
	CONSTRAINT `FK_TASK_DETAIL_OPERATOR_ID` FOREIGN KEY (`operator_id`) REFERENCES `user`(`rec_id`)
)ENGINE = INNODB DEFAULT CHARSET = utf8;



INSERT INTO `user`(`account`,`password`,`nickname`,`email`)
	VALUES('heatnan','1234','heat','964465194@qq.com');

	
INSERT INTO `module`(`type`,`name`,`deleted`,`created`)
	VALUES(1,'学习','0',NOW()),
		(2,'工作','0',NOW()),
		(3,'运动','0',NOW()),
		(4,'游玩','0',NOW()),
		(5,'经济','0',NOW()),
		(6,'生活','0',NOW()),
		(7,'其他','0',NOW());